name: "pull request actions"
on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - master

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: osa
  PROJECT_PATH: osa

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Deploy Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: build/web
          publish_branch: gh-pages
          destination_dir: ${{github.event.pull_request.number}}
          keep_files: true

  comment:
    name: PR Comment
    runs-on: ubuntu-latest
    needs: [export-web]
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Ссылка на билд: https://dreml.github.io/OneScreenAdventure/${{github.event.pull_request.number}}/'
            })

  telegram-notification:
    name: Telegram Notification
    runs-on: ubuntu-latest
    needs: [export-web]
    steps:
      - name: Send telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *Новый PR*
            Фича: ${{github.event.pull_request.title}}
            [Ссылка на PR](${{github.event.pull_request.html_url}})
            [Ссылка на игру](https://dreml.github.io/OneScreenAdventure/${{github.event.pull_request.number}}/)
