name: "pull request actions"
on:
  pull_request:
    types: [opened, reopened]

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: osa
  PROJECT_PATH: osa

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" ./build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Deploy Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: build/web
          publish_branch: gh-pages
          destination_dir: /${{github.event.pull_request.id}}/
          keep_files: true
          
  telegram-notification:
    name: Telegram Notification
    runs-on: ubuntu-latest
    needs: [export-windows, export-web]
    steps:
      - name: Send telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Новый PR
            Фича: ${{github.event.pull_request.title}}
            Ссылка на игру: https://dreml.github.io/${{github.event.pull_request.id}}/index.html
